# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Domotica(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: float=None, name: str=None, type: str=None):
        """
        Domotica - a model defined in Swagger

        :param id: The id of this Domotica.
        :type id: float
        :param name: The name of this Domotica.
        :type name: str
        :param type: The type of this Domotica.
        :type type: str
        """
        self.swagger_types = {
            'id': float,
            'name': str,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type'
        }

        self._id = id
        self._name = name
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Domotica':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Domotica of this Domotica.
        :rtype: Domotica
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """
        Gets the id of this Domotica.

        :return: The id of this Domotica.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """
        Sets the id of this Domotica.

        :param id: The id of this Domotica.
        :type id: float
        """

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this Domotica.

        :return: The name of this Domotica.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Domotica.

        :param name: The name of this Domotica.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """
        Gets the type of this Domotica.

        :return: The type of this Domotica.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this Domotica.

        :param type: The type of this Domotica.
        :type type: str
        """

        self._type = type

