# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DomoticaObject(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: float=None, name: str=None, type: str=None, description: str=None, creationdate: str=None):
        """
        DomoticaObject - a model defined in Swagger

        :param id: The id of this DomoticaObject.
        :type id: float
        :param name: The name of this DomoticaObject.
        :type name: str
        :param type: The type of this DomoticaObject.
        :type type: str
        :param description: The description of this DomoticaObject.
        :type description: str
        :param creationdate: The creationdate of this DomoticaObject.
        :type creationdate: str
        """
        self.swagger_types = {
            'id': float,
            'name': str,
            'type': str,
            'description': str,
            'creationdate': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'description': 'description',
            'creationdate': 'creationdate'
        }

        self._id = id
        self._name = name
        self._type = type
        self._description = description
        self._creationdate = creationdate

    @classmethod
    def from_dict(cls, dikt) -> 'DomoticaObject':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DomoticaObject of this DomoticaObject.
        :rtype: DomoticaObject
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """
        Gets the id of this DomoticaObject.

        :return: The id of this DomoticaObject.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """
        Sets the id of this DomoticaObject.

        :param id: The id of this DomoticaObject.
        :type id: float
        """

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this DomoticaObject.

        :return: The name of this DomoticaObject.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this DomoticaObject.

        :param name: The name of this DomoticaObject.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """
        Gets the type of this DomoticaObject.

        :return: The type of this DomoticaObject.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this DomoticaObject.

        :param type: The type of this DomoticaObject.
        :type type: str
        """

        self._type = type

    @property
    def description(self) -> str:
        """
        Gets the description of this DomoticaObject.

        :return: The description of this DomoticaObject.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """
        Sets the description of this DomoticaObject.

        :param description: The description of this DomoticaObject.
        :type description: str
        """

        self._description = description

    @property
    def creationdate(self) -> str:
        """
        Gets the creationdate of this DomoticaObject.

        :return: The creationdate of this DomoticaObject.
        :rtype: str
        """
        return self._creationdate

    @creationdate.setter
    def creationdate(self, creationdate: str):
        """
        Sets the creationdate of this DomoticaObject.

        :param creationdate: The creationdate of this DomoticaObject.
        :type creationdate: str
        """

        self._creationdate = creationdate

